#!/usr/bin/env ruby

root = File.dirname(File.dirname(__FILE__))
$:.unshift(File.join(root, 'lib'))

require 'rubygems'
require 'optparse'
require 'elasticsearch'
require 'pry'

Pry.config.prompt = [proc { "ies> " }, proc { "ies| " }]
Elasticsearch::Client.new(log: true).pry
